workflows:
  flutter_build:
    name: Flutter Build
    environment:
      flutter: 3.7.12
    scripts:
      - name: Build APK without sound null safety
        script: flutter build ipa --no-sound-null-safety